[development]

SECRET_KEY = "mysecretkey"
DEBUG = true

DATABASES__default__ENGINE = "django.db.backends.sqlite3"
DATABASES__default__NAME = "db.sqlite3"

CHANNEL_LAYERS__default__CONFIG__hosts = ["redis://:penduraai@localhost:6379/1"]

CACHES__default__LOCATION = "redis://:penduraai@localhost:6379/2"

CELERY_BROKER_URL = "redis://:penduraai@localhost:6379/3"

CORS_ORIGIN_ALLOW_ALL = true
