# Generated by Django 3.0.10 on 2020-10-06 12:08

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('profile', 'profile'), ('sheet', 'sheet'), ('record', 'record')], db_index=True, max_length=50, verbose_name='scope')),
                ('data', models.TextField(blank=True, default='{}', verbose_name='data')),
                ('expire_in', models.DateTimeField(db_index=True, verbose_name='expire in')),
                ('max_usage', models.SmallIntegerField(default=1, verbose_name='max usage')),
                ('usage', models.SmallIntegerField(default=0, verbose_name='usage')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
    ]
